### ISSUE TITLE
Create MongoDB

### ISSUE THREAD

**Issue by CodingRobIT** [CodingRobIT/glowing-spork#6]
For the beginning we need a MongoDB to work with our data. It is important to clarify whether we should move to an SQL database later and if so, which one.

**Comment by CodingRobIT** [comment]
One of us should just do it and give feedback when it's done.

**Comment by Vishnudas2003** [comment]
Hello,

Can you please assign this issue to me so that I can work on this issue. 

Thank you

**Comment by CodingRobIT** [comment]
I have created a DB, the Connections String from Mongo DB looks like this: 

mongodb+srv://KaHaRo:<password>@doitcluster1.cuse1ap.mongodb.net/DoIt?retryWrites=true&w=majority

ATTENTION!!! for future projects.
For whatever reason MongoDB Atlas says that the string looks like this 

mongodb+srv://KaHaRo:<Password>@doitcluster1.cuse1ap.mongodb.net/?retryWrites=true&w=majority here is missing before the ? Of course the DoIt varies depending on the name, for me it was in the Capstone gameapp e.g.


so the full String for IntelliJ should be like this:
MONGO_DB_URI=mongodb+srv://KaHaRo:<PW-HERE>@doitcluster1.cuse1ap.mongodb.net/DoIt?retryWrites=true&w=majority
